### PR TITLE
Create a javascript API (runs in node)

### PR DESCRIPTION
**Pull request by marcuswestin**
Import the node-kafka javascript client as a submodule at clients/javascript/node-kafka

### CODE REVIEW

**Comment by junrao** [comment]
Thanks for the contribution. Could you add the consumer part too?

**Comment by marcuswestin** [comment]
Yup! That's next on the list - not sure when I'll have my next kafka coding session, but it should be in the coming 2 weeks :)

I don't leave a job half done.

**Comment by marcuswestin** [comment]
I implemented the node-kafka javascript client at https://github.com/marcuswestin/node-kafka - this pull request imports it as a submodule into clients/javascript/node-kafka.

node-kafka implements both the Producer and the Consumer APIs.

Does this look good to your guys?

Cheers,
Marcus

**Comment by cburroughs** [comment]
Hi marcuswestin thanks for the contribution. Kafka has moved to the Apache Incubator.  Could you open a ticket at https://issues.apache.org/jira/browse/KAFKA ?

**Comment by marcuswestin** [comment]
totally, will do

**Comment by tommedema** [comment]
what's the status of this driver?

**Comment by junrao** [comment]
We have moved to Apache. Please submit your questions there.

http://incubator.apache.org/kafka/

Thanks,

Jun

**Pull request closed without merging**
