### PR TITLE
C++ Producer

### PR DESCRIPTION
**Pull request by quipo**
Hi,

here's a C++ library for a Kafka producer (with some tests created for the Boost Unit Test Framework).

HTH
## Best regards,

Lorenzo Alberton
Chief Tech Architect
MediaSift Ltd.

### CODE REVIEW

**Comment by kafka-dev** [comment]
Just committed this. Thanks.

**Comment by jkreps** [comment]
Hey Lorenzo, I wonder if you would be willing to update the headers on this code to have the apache license? We are trying to get everything cleaned up for our first apache release and this is required.

**Comment by quipo** [comment]
hi Jay, sure, I asked Ben (the author) to do it tomorrow morning.

## Best regards,

Lorenzo Alberton
Chief Tech Architect
MediaSift Ltd.

**Comment by jkreps** [comment]
Awesome! Thanks!

**Comment by quipo** [comment]
https://issues.apache.org/jira/browse/KAFKA-141?focusedCommentId=13124911&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13124911

https://issues.apache.org/jira/secure/attachment/12498566/cpp-license.patch

**Pull request merged**
