### PR TITLE
Kafka 12

### PR DESCRIPTION
**Pull request by jghoman**
Updated KafkaProducer.scala to no longer retry on IOException, but to close the connection immediately and re-throw exception.  Client will not be able to tell if send succeeded, but producer will no longer silently lose message.  

This logic was duplicated in both send and multiSend methods.  De-duplicated code by refactoring into common private send method.

Unit tests all pass.  This is not easily unit testable.  One could mock the BoundedByteBufferSend to throw an IOException and verify the exception isn't swallowed, but I think the change is simple enough to pass without verification.  I'm happy to do so, however, if others think it would be valuable.

### CODE REVIEW

**Comment by nehanarkhede** [comment]
changes look good ! will merge the patch

**Comment by junrao** [comment]
Once we catch the ioexception in send, we need to set channel to null. Otherwise the next send request won't try to establish a new socket connection.

Also, these two statements:
        channel = null
        this.channel = connect()
should be combined into one.

Also, a better way is probably to set channel to null in disconnect(). Then, disconnect() doesn't need an input parameter.

**Comment by jghoman** [comment]
Updated pull request:
- Merged statements by removing unnecessary null assignment.
- Refactored disconnect to not take parameters.  Doing this allowed... 
- Cleaned up disconnect  method.  Made it responsible for checking if channel == null, since this check was done before each call . Set channel to null in disconnect.  This better encapsulates disconnect()'s responsibility re: channel and makes calls to it cleaner.
- Noticed that the public close method was not synchronized, which could lead to race conditions if one thread closes in the middle of a call, which would set channel to null and cause an NPE in the send methods.  Synchronizing on lock in close corrects this behavior and  maintains the threadsafe contract.

**Comment by jghoman** [comment]
By the way, I notice a lot of code duplication between SimpleProducer and SimpleConsumer, including the close race condition.  Is there any interest in a patch to de-duplicate the code into a common trait?

**Comment by junrao** [comment]
Thanks, Jakob. I just merged your change to the main repository.

**Pull request merged**
