### PR TITLE
Changes to support ticket KAFKA-70, new configuration for log.retention.size

### PR DESCRIPTION
**Pull request by pmenon**
KAFKA-70 added log.retention.size to config with behaviour as specified in ticket

### CODE REVIEW

**Comment by jkreps** [comment]
Hey Pranath,

This looks great! We are in Apache now, so we have to follow their strange
and mysterious ways, which means using SVN and posting all the patches
against JIRA. So github is a little out of date now. I wonder if you could
make a patch against trunk and post a patch on the JIRA? Instructions are
here:
http://incubator.apache.org/kafka/contributing.html

I did a first patch and it looks good to me. This is a highly requested
feature, so we are very glad to have it.

Cheers,

-Jay

**Comment by pmenon** [comment]
Hey there,

Sure, I can do that.  But that sucks, I really like using GitHub and git in general.  SVN seems like a step back :(  

Anyways, I'll do a patch against the subversion trunk and submit that to the JIRA ticket.  I guess I can close this pull request as well?
- Prashanth

**Comment by jkreps** [comment]
Yeah but apache is a great community. You can use git svn to make the
patches, so hopefully the pain is not too much on contributors. And
hopefully someday Apache will step into the modern era...

-Jay

**Comment by cburroughs** [comment]
djunforgetable, there is also a pure git mirror available at http://git.apache.org/. We will deal with svn so you don't have to ;-)

**Comment by pmenon** [comment]
Hahaha, true.  In any case, I've attached the patch to the JIRA ticket here https://issues.apache.org/jira/browse/KAFKA-70 so I'll close this pull request.  Thanks for the heads up everyone :)
- Prashanth

**Pull request closed without merging**
